CREATE TABLE pessoa(
codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
ativo BOOLEAN NOT NULL,
logradouro VARCHAR(50),
bairro VARCHAR(50) NOT NULL,
numero BIGINT(20) NOT NULL,
complemento VARCHAR(50),
cep VARCHAR(50) NOT NULL,
cidade VARCHAR(50) NOT NULL,
estado VARCHAR(50) NOT NULL


) ENGINE=InnoDB DEFAULT CHARSET=utf8;

